contest_app/urls.py
from django.urls import path

from contest_app import views

app_name = 'contest'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('details/<int:pk>/', views.DetailsView.as_view(), name='details'),
    path('stage/<int:pk>/', views.StageView.as_view(), name='stage'),
    path('voting/<int:vote_id>/', views.vote, name='voting')

]

contests/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contests/', include('contest_app.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from user import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),

]

contest_app/models.py
from django.db import models
from django.contrib.auth.models import User
import enum


class MemberTypeEnum(enum.Enum):
    CONTENDER = "Contender"
    JURY = "Jury"
    ORGANIZER = "Organizer"


class Contest(models.Model):
    title = models.CharField(max_length=128)
    number_of_stages = models.IntegerField(default=0)

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    members = models.ManyToManyField(User, through="Membership")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["start_date"]


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    member_type = models.CharField(
        max_length=25, choices=[(tag, tag.value) for tag in MemberTypeEnum]
    )

    def __str__(self):
        return str(self.user)


class Stage(models.Model):
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    stage_no = models.IntegerField()

    def __str__(self):
        return f"{self.contest}/stage_{self.stage_no}"


class Vote(models.Model):
    jury = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    contender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE)

    points = models.IntegerField(default=0)

    def __str__(self):
        return f"jury{self.jury}/contender_{self.contender}/stage_{self.stage}/points_{self.points}"

user/models.py
from django.db import models

# Create your models here.

contest_app/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, get_list_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView

from contest_app.models import Contest, Vote, Stage


class IndexView(ListView):
    template_name = "contest_app/index.html"
    context_object_name = "latest_contest_list"
    model = Contest


class DetailsView(DetailView):
    template_name = "contest_app/details.html"
    context_object_name = "contest"
    model = Contest

    def get_all_jurys_for_contest(self):
        return self.object.membership_set.filter(member_type="J")

    def get_all_contenders_for_contest(self):
        return self.object.membership_set.filter(member_type="C")

    def get_all_stages_for_contest(self):
        return get_list_or_404(Stage, contest=self.object.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"jurys": self.get_all_jurys_for_contest()})
        context.update({"contenders": self.get_all_contenders_for_contest()})
        context.update({"stages": self.get_all_stages_for_contest()})
        return context


class StageView(DetailView):
    model = Stage
    context_object_name = 'stage'
    template_name = 'contest_app/vote.html'

    def get_all_votes(self):
        return Vote.objects.filter(stage=self.object.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"votes": self.get_all_votes()})
        return context


def vote(request, vote_id):
    vote = get_object_or_404(Vote, pk=vote_id)

    # TODO: Dodać Form i validator
    try:
        points = int(request.POST['points'])
    except KeyError as e:
        messages.add_message(request, messages.ERROR, 'Problem with finding points')
        return HttpResponseRedirect(reverse(f'contest:stage', args=(vote.stage.contest.pk,)))
    except TypeError as e:
        messages.add_message(request, messages.ERROR, 'Point cant be casted to int')
        return HttpResponseRedirect(reverse(f'contest:stage', args=(vote.stage.contest.pk,)))

    if vote.points != 0:
        messages.add_message(request, messages.ERROR, 'Vote already submitted')
        return HttpResponseRedirect(reverse(f'contest:stage', args=(vote.stage.contest.pk,)))
    if points < 0:
        messages.add_message(request, messages.ERROR, 'Vote cant be negative')
        return HttpResponseRedirect(reverse(f'contest:stage', args=(vote.stage.contest.pk,)))

    vote.points = points
    vote.save()
    messages.add_message(request, messages.INFO, 'Vote processed')

    return HttpResponseRedirect(reverse(f'contest:stage', args=(vote.stage.contest.pk,)))

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect(reverse('contest:index'))
    else:
        form = UserCreationForm()
    return render(request, 'user/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user=user)
            return redirect(reverse('contest:index'))
        else:
            messages.WARNING('User not found')
            return render(request, reverse('user:login'))
    return render(request, 'user/login.html')

templates/contest_app/details.html
<p>Contest name: {{ contest }}</p>
{% for stage in stages %}
    <p>Stages: <a href="{% url 'contest:stage' stage.id %}">{{ stage.stage_no }}</a></p>
{% endfor %}

<p> Jurys </p>
<ul>
{% for jury in jurys  %}
    <li><p>{{ jury }}</p></li>
{% endfor %}
</ul>
<p> Contenders </p>

<ul>
{% for contender in contenders  %}
    <li><p>{{ contender }}</p></li>
{% endfor %}
</ul>

templates/contest_app/index.html
<ul>
{% for contest in latest_contest_list %}
    <li><a href="{% url 'contest:details' contest.id   %}">{{contest}}</a></li>
{% endfor %}
</ul>

templates/contest_app/vote.html
<p>Contenders</p>
{% if messages%}
    {% for message in messages  %}
            <p> {{message.tags}} : {{message}}</p>
    {% endfor %}
{% endif %}

{% for vote in votes%}
<form action="{% url 'contest:voting' vote.pk %}" method="post">
    {% csrf_token %}
    <label for="vote{{vote.id}}"> {{vote.contender}} </label>
    <input type="range" min="0" max="10" value="{{vote.points}}" name="points" id="vote{{vote.id}}" >
    <input type="submit" value="Vote"><br>
</form>
{% endfor %}

templates/user/login.html
{% if messages%}
    {% for message in messages  %}
            <p> {{message.tags}} : {{message}}</p>
    {% endfor %}
{% endif %}

<form method="post" action="{% url 'user:login' %}">
    {% csrf_token %}

    <label for="username" > Username </label>
    <input type='text' name="username" id="username" ><br>
    <label for="password" > Password </label>
    <input type='password' name="password" id="password" ><br>
    <input type="submit" value="Login"><br>

</form>

templates/user/signup.html
{{form.errors}}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
    <input type="submit" value="SignIn">
</form>